### ISSUE TITLE
error 99

### ISSUE THREAD

**Issue by Dispasim** [SFeli/ESP32_S8#1]
Hello, I bought an esp 32 and a senseair s8 for a school project and tryied your code. But I only have an error 99 and don't know why. what does it mean exactly ? thank you in advance  for your answer.
Eliot

**Comment by ruben2s** [comment]
Same here :( Have you managed to fix it?

**Comment by Dispasim** [comment]
sadly not :(

**Comment by SFeli** [comment]
Hi Dispasim and Ruben2s,
the Error 99 indicates that the CRC is wrong. 
This could be the connection between the S8 and the ESP32.
Just for doublecheck the current Environment - with Arduino IDE 2.0.1 and Board DOIT ESP32 DEVKIT V1 it works.
Question 1: Which developtment platform you are using? Arduion with the .ino ?
Question 2: What appears on the serial monitor (115200 baud) ? 
12:11:13.016 -> 
12:11:13.016 -> ABC-Tage: 180
12:11:13.063 -> Sensor ID : 071dbfe4
12:11:13.155 -> FirmWare  : 0178
12:11:13.326 -> Registerwert : fe4400 01 029975 -> (d) 108 210 -> (x) 6c d2 ->(Wert) 27858 -> (t) l    Ende  

Sorry for my delay.

Stefan

**Comment by SFeli** [comment]
too old and no answert

**Comment by Dispasim** [comment]
> too old and no answert

Hey sorry for no response. Turn out my sensor was defective and I had to buy an other one.
