### ISSUE TITLE
merci

### ISSUE THREAD

**Issue by stef-ladefense** [SFeli/ESP32_S8#2]
thank for your program ! work very well
use portion of your code for S8 and ESP32S2, with Arduino ESP32 Version 2.0.3-RC1

**Comment by SFeli** [comment]
Hi Stef-ladefense,
thx can we close the #2 - Issue ? - In the coding I have made some adjustemnsts - perhaps herlpfull for you.
Regards
Stefan

**Comment by SFeli** [comment]
No issue.

**Comment by stef-ladefense** [comment]
thank you very much, I just looked at the INO, the algorithm does not change, it is only cosmetic changes?
