### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by Shohreh** [SFeli/ESP32_S8#3]
Hello,

In the following sentence, I guess you meant 256, not 265: "The requested value is in byte 3 and 4 (0x03) and (0x88) with low-byte first. so 88 * 265 + 03. .. followed by two byte for CRC."

Other typos:
"There is no standard library aviable"
"lenght"
"the frist"

Cheers,

**Comment by SFeli** [comment]
Thx Shohreh,

have accepted all your hinst. 
Regards Stefan
